services:
  fewa-web-app:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    restart: always
    ports:
      - "8081:8081"
    environment:
      DATABASE_URL: postgres://myuser:mypassword@postgres:5432/fewa
      EXPO_PUBLIC_API_URL: http://localhost:8081
      NODE_ENV: production
      PORT: 8081
    command: ["bun", "/app/express-server.js"]
    depends_on:
      - database
    networks:
      - fewa-internal-network

  database:
    image: postgres:latest
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: fewa
    volumes:
      - fewa_pg_data:/var/lib/postgresql/data
    networks:
      - fewa-internal-network

  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    volumes:
      - ../web-server/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - fewa-web-app
    ports:
      - "80:80"
    networks:
      - fewa-internal-network

networks:
  fewa-internal-network:
    driver: bridge

volumes:
  fewa_pg_data:
