name: Build Web App

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+-[0-9]+"
  workflow_dispatch:

jobs:
  build-web:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Cache Docker images
        id: docker-cache
        uses: ScribeMD/docker-cache@0.5.0
        with:
          key: docker-${{ runner.os }}

      - name: Build and push Docker image
        if: steps.docker-cache.outputs.cache-hit != 'true'
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./docker/Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/fewa-web-app:${{ github.ref_name }}
            ${{ secrets.DOCKERHUB_USERNAME }}/fewa-web-app:latest
          secrets: |
            PORT=${{ secrets.PORT }}
            NODE_ENV=${{ secrets.NODE_ENV }}
            DATABASE_URL=${{ secrets.DATABASE_URL }}
