name: Build Web App

on:
  push:
    branches:
      - master

env:
  PORT: ${{ vars.PORT }}
  NODE_ENV: ${{ vars.NODE_ENV }}
  DATABASE_URL: ${{ secrets.DATABASE_URL }}
  DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME  }}
  DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN  }}

jobs:
  build-web:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Cache Bun dependencies
        id: cache-node-modules
        uses: actions/cache@v4
        with:
          path: ~/.bun/install/cache
          key: ${{ runner.os }}-bun-${{ hashFiles('**/bun.lockb') }}
          restore-keys: ${{ runner.os }}-bun-

      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.1.37

      - name: Install dependencies
        if: steps.cache-node-modules.outputs.cache-hit != 'true'
        run: bun install --frozen-lockfile

      - name: Build expo web app
        run: bun build:web

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ env.DOCKERHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/arm64
          file: ./docker/Dockerfile
          push: true
          tags: |
            ${{ env.DOCKERHUB_USERNAME }}/fewa-web-app:${{ github.ref_name }}
            ${{ env.DOCKERHUB_USERNAME }}/fewa-web-app:latest
          cache-from: type=registry,ref=${{ env.DOCKERHUB_USERNAME }}/fewa-web-app:latest
          cache-to: type=inline
          secrets: |
            PORT=${{ env.PORT }}
            NODE_ENV=${{ env.NODE_ENV }}
            DATABASE_URL=${{ env.DATABASE_URL }}
